import 'dart:io';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

import '../models/group.dart';
import '../models/loan_progress.dart';
import '../models/report.dart';

enum ReportFormat { pdf, excel }

/// Renders a [GroupReport] as a PDF or an Excel workbook, both carrying a
/// "vBank" watermark, and hands the file to the platform (share sheet on
/// phones, Downloads folder on desktops).
class ReportExportService {
  static const _brand = 'vBank';

  String _money(String c, double v) => '$c ${v.toStringAsFixed(2)}';
  String _date(DateTime d) =>
      '${d.year}-${d.month.toString().padLeft(2, '0')}-${d.day.toString().padLeft(2, '0')}';

  List<(String, String)> _summaryRows(Group group, GroupReport r, GroupFund? fund) {
    final c = group.config.currency;
    return [
      ('Group', group.name),
      ('Period', '${_date(r.period.start)} to ${_date(r.period.end.subtract(const Duration(days: 1)))}'),
      ('Members', '${group.memberCount}'),
      ('Contributions received', _money(c, r.totalContributions)),
      ('Loans paid out', _money(c, r.totalLoansDisbursed)),
      ('Repayments received', _money(c, r.totalLoansRepaid)),
      ('Penalties', _money(c, r.totalPenalties)),
      ('Net change in fund', _money(c, r.netFundChange)),
      ('Group fund', _money(c, fund?.total ?? r.groupFundBalance)),
      if (fund != null) ('Available to lend', _money(c, fund.available)),
      if (fund != null) ('Out on loan', _money(c, fund.lentOut)),
      ('Meetings held', '${r.totalMeetings}'),
      ('Transactions recorded', '${r.totalTransactions}'),
    ];
  }

  // ---------------------------------------------------------------- PDF ---

  Future<Uint8List> buildPdf({required Group group, required GroupReport report, GroupFund? fund}) async {
    final c = group.config.currency;
    final doc = pw.Document(title: '${group.name} report', author: _brand, creator: _brand);
    final ink = PdfColor.fromHex('#0B0B0C');
    final muted = PdfColors.grey600;
    final hairline = PdfColors.grey300;
    final generated = DateTime.now();

    doc.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.fromLTRB(40, 44, 40, 40),
          theme: pw.ThemeData.withFont(base: pw.Font.helvetica(), bold: pw.Font.helveticaBold()),
          // Watermark: the brand, rotated and faint, behind every page.
          buildBackground: (context) => pw.FullPage(
            ignoreMargins: true,
            child: pw.Center(
              child: pw.Transform.rotate(
                angle: 0.55,
                child: pw.Opacity(
                  opacity: 0.07,
                  child: pw.Text(_brand, style: pw.TextStyle(fontSize: 160, fontWeight: pw.FontWeight.bold, color: ink)),
                ),
              ),
            ),
          ),
        ),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(group.name, style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: ink)),
                pw.Text(_brand, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: muted)),
              ],
            ),
            pw.SizedBox(height: 2),
            pw.Text(
              'Group report · ${_date(report.period.start)} to ${_date(report.period.end.subtract(const Duration(days: 1)))}',
              style: pw.TextStyle(fontSize: 10, color: muted),
            ),
            pw.SizedBox(height: 10),
            pw.Divider(color: hairline, thickness: 0.6),
            pw.SizedBox(height: 8),
          ],
        ),
        footer: (context) => pw.Column(children: [
          pw.Divider(color: hairline, thickness: 0.6),
          pw.SizedBox(height: 4),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Generated by $_brand on ${_date(generated)}', style: pw.TextStyle(fontSize: 8, color: muted)),
              pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: pw.TextStyle(fontSize: 8, color: muted)),
            ],
          ),
        ]),
        build: (context) => [
          _sectionTitle('Summary', muted),
          pw.TableHelper.fromTextArray(
            border: null,
            headerCount: 0,
            cellPadding: const pw.EdgeInsets.symmetric(vertical: 5, horizontal: 4),
            cellStyle: pw.TextStyle(fontSize: 10, color: ink),
            cellAlignments: {0: pw.Alignment.centerLeft, 1: pw.Alignment.centerRight},
            columnWidths: {0: const pw.FlexColumnWidth(2), 1: const pw.FlexColumnWidth(3)},
            rowDecoration: pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: hairline, width: 0.5))),
            data: [for (final row in _summaryRows(group, report, fund)) [row.$1, row.$2]],
          ),
          pw.SizedBox(height: 22),
          _sectionTitle('Member statements', muted),
          pw.TableHelper.fromTextArray(
            border: null,
            headerStyle: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: muted),
            headerDecoration: pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: ink, width: 0.8))),
            cellStyle: pw.TextStyle(fontSize: 10, color: ink),
            cellPadding: const pw.EdgeInsets.symmetric(vertical: 5, horizontal: 4),
            cellAlignments: {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.centerRight,
              2: pw.Alignment.centerRight,
              3: pw.Alignment.centerRight,
              4: pw.Alignment.centerRight,
            },
            rowDecoration: pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: hairline, width: 0.5))),
            headers: ['Member', 'Contributed ($c)', 'Borrowed ($c)', 'Repaid ($c)', 'Still owed ($c)'],
            data: [
              for (final s in report.memberStatements)
                [
                  s.memberName,
                  s.totalContributed.toStringAsFixed(2),
                  s.totalLoaned.toStringAsFixed(2),
                  s.totalRepaid.toStringAsFixed(2),
                  s.outstandingBalance.toStringAsFixed(2),
                ],
            ],
          ),
        ],
      ),
    );
    return doc.save();
  }

  pw.Widget _sectionTitle(String text, PdfColor color) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 6),
        child: pw.Text(text.toUpperCase(), style: pw.TextStyle(fontSize: 8.5, letterSpacing: 1.2, fontWeight: pw.FontWeight.bold, color: color)),
      );

  // -------------------------------------------------------------- Excel ---

  /// A minimal Office Open XML workbook (two sheets, bold headers, a number
  /// format for money) written by hand: the popular `excel` package pins an
  /// old `archive` that clashes with the IPFS stack. The "watermark" is a
  /// brand banner on each sheet plus a page header that prints on every page.
  Future<Uint8List> buildXlsx({required Group group, required GroupReport report, GroupFund? fund}) async {
    final c = group.config.currency;
    final summary = <List<_Cell>>[
      [_Cell.text('$_brand · ${group.name} · group report', style: 3)],
      [_Cell.text('Generated ${_date(DateTime.now())}', style: 4)],
      [],
      for (final row in _summaryRows(group, report, fund)) [_Cell.text(row.$1, style: 1), _Cell.text(row.$2)],
    ];
    final members = <List<_Cell>>[
      [_Cell.text('$_brand · ${group.name} · member statements', style: 3)],
      [_Cell.text('Amounts in $c', style: 4)],
      [],
      [for (final h in ['Member', 'Contributed', 'Borrowed', 'Repaid', 'Still owed']) _Cell.text(h, style: 1)],
      for (final s in report.memberStatements)
        [
          _Cell.text(s.memberName),
          _Cell.number(s.totalContributed),
          _Cell.number(s.totalLoaned),
          _Cell.number(s.totalRepaid),
          _Cell.number(s.outstandingBalance),
        ],
    ];

    final archive = Archive()
      ..addFile(_file('[Content_Types].xml', _contentTypes))
      ..addFile(_file('_rels/.rels', _rootRels))
      ..addFile(_file('docProps/app.xml', _appProps))
      ..addFile(_file('xl/workbook.xml', _workbook(['Summary', 'Members'])))
      ..addFile(_file('xl/_rels/workbook.xml.rels', _workbookRels(2)))
      ..addFile(_file('xl/styles.xml', _styles))
      ..addFile(_file('xl/worksheets/sheet1.xml', _sheet(summary, widths: [28, 40])))
      ..addFile(_file('xl/worksheets/sheet2.xml', _sheet(members, widths: [28, 16, 16, 16, 16])));
    final bytes = ZipEncoder().encode(archive);
    return Uint8List.fromList(bytes);
  }

  ArchiveFile _file(String name, String content) => ArchiveFile.string(name, content);

  static String _esc(String s) => s
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;');

  static String _colName(int i) {
    var n = i + 1;
    var s = '';
    while (n > 0) {
      final r = (n - 1) % 26;
      s = String.fromCharCode(65 + r) + s;
      n = (n - 1) ~/ 26;
    }
    return s;
  }

  String _sheet(List<List<_Cell>> rows, {required List<double> widths}) {
    final b = StringBuffer()
      ..write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>')
      ..write('<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">')
      ..write('<sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews>')
      ..write('<cols>');
    for (var i = 0; i < widths.length; i++) {
      b.write('<col min="${i + 1}" max="${i + 1}" width="${widths[i]}" customWidth="1"/>');
    }
    b.write('</cols><sheetData>');
    for (var r = 0; r < rows.length; r++) {
      if (rows[r].isEmpty) continue;
      b.write('<row r="${r + 1}">');
      for (var col = 0; col < rows[r].length; col++) {
        final cell = rows[r][col];
        final ref = '${_colName(col)}${r + 1}';
        if (cell.number != null) {
          b.write('<c r="$ref" s="2"><v>${cell.number}</v></c>');
        } else {
          b.write('<c r="$ref" s="${cell.style}" t="inlineStr"><is><t>${_esc(cell.text ?? '')}</t></is></c>');
        }
      }
      b.write('</row>');
    }
    b
      ..write('</sheetData>')
      ..write('<pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>')
      // Prints the brand on every page — the closest thing a spreadsheet has to a watermark.
      ..write('<headerFooter><oddHeader>&amp;C&amp;"-,Bold"&amp;K9A9A9A$_brand</oddHeader>'
          '<oddFooter>&amp;LGenerated by $_brand&amp;RPage &amp;P of &amp;N</oddFooter></headerFooter>')
      ..write('</worksheet>');
    return b.toString();
  }

  static const _contentTypes = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
      '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
      '<Default Extension="xml" ContentType="application/xml"/>'
      '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
      '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
      '<Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
      '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
      '<Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>'
      '</Types>';

  static const _rootRels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
      '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
      '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>'
      '</Relationships>';

  static const _appProps = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">'
      '<Application>$_brand</Application></Properties>';

  String _workbook(List<String> names) {
    final b = StringBuffer()
      ..write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>')
      ..write('<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
          'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>');
    for (var i = 0; i < names.length; i++) {
      b.write('<sheet name="${_esc(names[i])}" sheetId="${i + 1}" r:id="rId${i + 1}"/>');
    }
    b.write('</sheets></workbook>');
    return b.toString();
  }

  String _workbookRels(int sheets) {
    final b = StringBuffer()
      ..write('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>')
      ..write('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">');
    for (var i = 1; i <= sheets; i++) {
      b.write('<Relationship Id="rId$i" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" '
          'Target="worksheets/sheet$i.xml"/>');
    }
    b.write('<Relationship Id="rId${sheets + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>');
    b.write('</Relationships>');
    return b.toString();
  }

  /// cellXfs: 0 normal · 1 bold · 2 money (#,##0.00) · 3 title · 4 muted note.
  static const _styles = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
      '<numFmts count="1"><numFmt numFmtId="164" formatCode="#,##0.00"/></numFmts>'
      '<fonts count="4">'
      '<font><sz val="11"/><name val="Calibri"/></font>'
      '<font><b/><sz val="11"/><name val="Calibri"/></font>'
      '<font><b/><sz val="14"/><name val="Calibri"/></font>'
      '<font><sz val="10"/><color rgb="FF808080"/><name val="Calibri"/></font>'
      '</fonts>'
      '<fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills>'
      '<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>'
      '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
      '<cellXfs count="5">'
      '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>'
      '<xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/>'
      '<xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>'
      '<xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"/>'
      '<xf numFmtId="0" fontId="3" fillId="0" borderId="0" xfId="0" applyFont="1"/>'
      '</cellXfs>'
      '<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>'
      '</styleSheet>';

  // ------------------------------------------------------------ Deliver ---

  /// Builds the file and hands it over: share sheet on phones, saved to the
  /// Downloads folder (and opened) on desktops. Returns the path written.
  Future<String> export({
    required Group group,
    required GroupReport report,
    GroupFund? fund,
    required ReportFormat format,
  }) async {
    final bytes = switch (format) {
      ReportFormat.pdf => await buildPdf(group: group, report: report, fund: fund),
      ReportFormat.excel => await buildXlsx(group: group, report: report, fund: fund),
    };
    final safeName = group.name.replaceAll(RegExp(r'[^A-Za-z0-9._-]+'), '-');
    final ext = format == ReportFormat.pdf ? 'pdf' : 'xlsx';
    final fileName = 'vbank-$safeName-${_date(DateTime.now())}.$ext';
    final mobile = Platform.isAndroid || Platform.isIOS;
    final dir = mobile ? await getTemporaryDirectory() : (await getDownloadsDirectory() ?? await getApplicationDocumentsDirectory());
    final file = File(p.join(dir.path, fileName));
    await file.writeAsBytes(bytes, flush: true);
    if (mobile) {
      await Share.shareXFiles(
        [XFile(file.path, mimeType: format == ReportFormat.pdf ? 'application/pdf' : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')],
        subject: '${group.name} report',
      );
    } else {
      try {
        await launchUrl(Uri.file(file.path));
      } catch (_) {
        // Saved anyway; the caller shows the path.
      }
    }
    return file.path;
  }
}

class _Cell {
  final String? text;
  final double? number;
  final int style;
  const _Cell.text(this.text, {this.style = 0}) : number = null;
  const _Cell.number(this.number) : text = null, style = 2;
}
